Sprint1
KateSolodchuk/Project_beauty pull request #1
Opened 2023-03-26 07:07 UTC by KateSolodchuk

Я заранее прошу прощения за то, как это выглядит, с гитхабом все не получалось до последнего, поэтому коммитов почти нет. Собственно, и сам код... В общем, мне нужна не столько проверка, сколько помощь. Половину я вообще сделала каким-то волшебным образом, сама не понимая, как.

2023-03-29 15:16 UTC, euge-huge commented
Сообщение выше от GIT говорит, что есть конфликт с веткой, в которую вливаются изменения (с веткой main в твоем случае)

Нужно либо выполнить команду  `git merge main` и решить конфликт (у Кости должна быть инструкция)
Или можно прям здесь нажать на кнопку Resolve confilcts (на скрине)
<img width="826" alt="image" src="https://user-images.githubusercontent.com/58856916/228585859-2be9adc4-9ce6-46e6-b76f-0cfa4e9c8472.png">

И оставить нужные строки)

2023-03-29 15:20 UTC, KateSolodchuk commented
Поменяла инфу в файле readme, насколько вижу, конфликт исчерпан)

2023-03-29 15:22 UTC, euge-huge commented
Также обрати внимание, что сейчас изменения, которые отображаются в PR меняют файлы в main, потому что работа велась сначала там, а только потом была создана ветка, в идеале должно было быть, чтобы все файлы в этом PR отображались как новые)

Менять ничего не нужно, но это на светлое дальнейшее будущее, главное что удалось разобраться с git, дальше понимания будет только больше))

2023-03-29 16:24 UTC, euge-huge requested changes
Для начала очень хорошо!

Есть, что поправить и еще больше приблизиться к макету =)

Так держать!

2023-03-29 16:24 UTC, euge-huge commented on index.html
> +            <div class="advantages-item">
`стиль кода` `можно лучше`

Обычно не принято разделять начало блока пустой строкой, а вот делать пустые строки между блоками, которые сливаются - хороший тон.

Например:
```
<div class="block">
  <div class="title"></div>

  <img>

  <div class="description></div>
</div>
```

Но не нужно этим злоупотреблять =)
Например элементы, которые являются очень подобными друг другу, лучше оставлять друг за другом, списки, ссылки и тд

Например 
```
<ul class="list">
  <li></li>
  <li></li>
  <li></li>
</ul>
```

2023-03-29 16:24 UTC, euge-huge commented on img/косметос.png
`можно лучше`

Желательно не использовать русские слова в названиях файла)

P.S. Для других файлов тоже поправить лучше

2023-03-29 16:24 UTC, euge-huge commented on main.css
> +
`нужно поправить`

Чтобы всегда по центру было не совсем корректный margin

Что то подобное должно быть:
```
.container {
     width: 100%;
     max-width: 1110px;
     margin: 0 auto;
 }
```

2023-03-29 16:24 UTC, euge-huge commented on main.css
> +.navigation ul li a {
`нужно поправить`

Лучше избегать такие вложенности, ведь если мы в html добавим еще один "слой", то эти стили перестанут работать(

Поэтому лучше добавить еще один класс отдельный конкретно для этого <a> и добавить его в html!

P.S. Это поправить во всем файле :3

2023-03-29 16:24 UTC, euge-huge commented on main.css
> +}
`можно лучше`

У ul лучше убрать padding еще, он всегда у него есть по умолчанию, чтобы элементы всегда в центре были)

2023-03-29 16:24 UTC, euge-huge commented on main.css
> +
`можно лучше`

Лучше избегать пустых ненужных строк в файлах, нарушается читаемость кода)

2023-03-29 16:24 UTC, euge-huge commented on main.css
> +}
`нужно поправить`

Глобальные стили, которые будут применены ко всем элементам таких сущностей лучше выносить в самое начало файла (там где body html и др), так они более заметны)

2023-03-29 16:24 UTC, euge-huge commented on main.css
> +    margin-bottom: 15px;
`нужно поправить`

Нужно добавить цвет как в макете, чтобы он не был такой синий)

2023-03-29 16:24 UTC, euge-huge commented on index.html
> +                    <li><a href="#">Контакты</a></li>
`нужно поправить`

Здесь нужно стилизовать :hover для этих элементов, чтобы они были зелененькие, когда мы на них наводимся)

2023-03-29 16:24 UTC, euge-huge commented on index.html
> +                <ul>
Попробуй добавить в стилях для него `flex-wrap: wrap;` и `gap: 8px 0;`, чтобы если мы добавили еще много элементов, то увидели что-то подобное:

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/58856916/228598489-25db2a16-a6da-46a3-9f81-d916f68f5d60.png">

Для логотипа и телефона я добавил
`min-width: fit-content`, чтобы они не уменьшались

2023-03-29 16:24 UTC, euge-huge commented on main.css
> +}
`нужно поправить`

Для этого лучше использовать общий .container, который у тебя уже есть

Можно добавить margin: 0 auto; в этот, тоже будет работать (будет по центру), но лучше общий .container

2023-03-29 16:24 UTC, euge-huge commented on main.css
> +}
`нужно поправить`

То же что и для .main-container =)

2023-03-29 16:24 UTC, euge-huge commented on index.html
> +        </div>
`нужно поправить`

Девушку вынести на один уровень выше, в блок <div class="container"> и задать ему position: relative; а классу girl сделать не left: ...px, а right: ...px

Тут потренироваться нужно хорошо, чтобы ничего не скакало на странице, если изменить размер экрана)

2023-03-29 16:24 UTC, euge-huge commented on index.html
> +        </div>
`нужно поправить`

Ограничить по размеру, чтобы если добавить текст, он бы не заежал под девушку:

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/58856916/228601226-1f63aea2-cc7e-45be-8ff8-95729efa891f.png">

2023-03-29 16:24 UTC, euge-huge commented on main.css
> +    border-radius: 24px;
`нужно поправить`

Нужно убрать у кнопки обводку, `border: none`
Добавить `cursor: pointer`

2023-03-29 16:24 UTC, euge-huge commented on main.css
> +    height: 66px;
`нужно поправить`

Избавиться от большинства height у блоков, потому что они ограничивают его размер, хотя контента там больше, чем на 66px высотой)

2023-03-29 16:24 UTC, euge-huge commented on main.css
> +    height: 176px;
Тоже убрать высоту, она должна сама тянуться от размера контейнеров)

2023-03-29 16:24 UTC, euge-huge commented on main.css
> +    max-height: 860px;
Тоже убрать высоту, она должна сама тянуться от размера контейнеров)

2023-03-29 16:24 UTC, euge-huge commented on main.css
> +}
После этого, можно попробовать прийти к такому виду, если добавить еще карточки:

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/58856916/228603025-62fcd470-827a-4985-97de-e059c576f84d.png">

Это произойдет, если убрать лишние, ограничивающие высоты, и добавить этому блоку ` flex-wrap: wrap;`

2023-03-29 16:24 UTC, euge-huge commented on index.html
> +                <div class="video">
`нужно поправить`

 Сделать cursor: pointer;

2023-03-29 16:24 UTC, euge-huge commented on index.html
> +                <div class="video">
Также лучше ограничить изображение в размерах, чтобы оно не растягивалось и не мешало другим блокам, если его заменить)

<img width="1351" alt="image" src="https://user-images.githubusercontent.com/58856916/228603819-664ca59d-e467-46b9-a359-776c8bf0143d.png">

Сделать border-radius, чтобы края были закруглены как в макете)

2023-03-30 08:29 UTC, KateSolodchuk commented
Сделала все по твоему списку, спасибо! Стало гораздо понятнее)
Но! Беспокоит две оставшиеся очевидные штуки.
1) Текст над кнопкой я ограничила вроде и по ширине, и по высоте:
.credo-promise {
    font-size: 20px;
    color: #333333;
    margin-bottom: 59px;
    line-height: 24px;
    max-width: 315px;
    max-height: 24px;
}

Но если добавить lorem, он теперь ползет под кнопку, не понимаю, почему.

![Screenshot_26](https://user-images.githubusercontent.com/128446989/228776182-f70b8a36-b945-431e-b173-39807b8a3e4d.png)

2) Когда размер не полноэкранный, подвал точно ведел себя норм, контент - не уверена, а вот шапка не норм, обрезается и она сама, и девушка. Что я делаю не так?

![Screenshot_27](https://user-images.githubusercontent.com/128446989/228776978-e581033f-9b71-4031-ba5c-aa9419fa084e.png)

2023-04-08 09:44 UTC, euge-huge commented
> Сделала все по твоему списку, спасибо! Стало гораздо понятнее) Но! Беспокоит две оставшиеся очевидные штуки.
> 
> 1. Текст над кнопкой я ограничила вроде и по ширине, и по высоте:
>    .credo-promise {
>    font-size: 20px;
>    color: #333333;
>    margin-bottom: 59px;
>    line-height: 24px;
>    max-width: 315px;
>    max-height: 24px;
>    }
> 
> Но если добавить lorem, он теперь ползет под кнопку, не понимаю, почему.
> 
> ![Screenshot_26](https://user-images.githubusercontent.com/128446989/228776182-f70b8a36-b945-431e-b173-39807b8a3e4d.png)
> 
> 2. Когда размер не полноэкранный, подвал точно ведел себя норм, контент - не уверена, а вот шапка не норм, обрезается и она сама, и девушка. Что я делаю не так?
> 
> ![Screenshot_27](https://user-images.githubusercontent.com/128446989/228776978-e581033f-9b71-4031-ba5c-aa9419fa084e.png)

1. по высоте не нужно ограничивать блок с текстом, пусть растягивается вниз, это нормальное поведение

2.  Нужно сделать max-width,вметсо просто width у классов .advantages-container и у .main-container, они мешают уменьшатся контенту: поэтому белая линия справа появляется.

Также рекомендую добавить для класса .header position: relative; А у класса .header-girl изменить position: relative; на position: absolute; и сделать bottom: 0px чтобы женщина точно была спозиционирована.

2023-04-08 09:45 UTC, euge-huge approved these changes

2023-04-09 09:11 UTC, merged